### PR TITLE
Data generator Skill

### PR DESCRIPTION
**Pull request by bpandey-CS**
This is an example that proposes a generic Data generator that uses hadron, we can aim to generate different kinds of data sets, just by using the right Domain Contract and hadron_kwargs

### CODE REVIEW

**Comment by pkandarpa-cs** [comment]
is there is a diagram that walks through how we compile the larger files - that is also important

**Comment by Gigas64** [comment]
I haven't managed to catch up with Bikash to respond to what in essence is his code but as a general comment the size of, or number of rows in, a synthetic file can be set in the payload of the skill. The skill itself is a set of instructions on how to build a synthetic data row, whose activation and monitoring is determined by Fabric and the orchestration therein. Bikash will be able to provide you with reports that describe the set of instructions within his skill as part of the standard reporting insight. This would be the same for any synthetically generated data

**Comment by Gigas64** [comment]
Your second query is a good one and though this doesn't answer it directly, might help with some insight or raise other questions. The size of a synthetic file is determined by the type of testing being done with the synthetic builder focused much more on volume and system testing rather than data ingestion. Synthetically generated files are limited in size to roughly 100Mb. But the files themselves are contiguous which means we can produce multiple files relating to a common data stream. This means we could do volume or system testing to any size we require, as recently demonstrated with CVS. Ingestion testing can still be done but requires a second step of concatenating all the files together into one larger one. I hope this is useful

**Comment by Gigas64** [comment]
I appreciate I haven't answered your question about screenshots and diagrams but hopefully this will give some context to any diagrams and screenshots you get from Bikash

**Comment by pkandarpa-cs** [comment]
Thanks @Gigas64 that does help us understand more about how hadron does things internally.

**Review by pkandarpa-cs — APPROVED** [review]

**Comment by bpandey-CS** [comment]
https://user-images.githubusercontent.com/86944879/162190752-1134c3c7-77c5-4655-9e4c-bfad349d0e02.mp4

This is a demonstration of using this skill for one particular domain contract, this domain contract has the data information and the steps to generate the three files we need in one go, this we can have more such contracts run by this same skill which behave differently for ex, generating a data with 1:many relationship where the first file is generated in one go but the next set of files are generated gradually in a repetitive manner.

**Pull request merged**
