### PR TITLE
Fab 2607:  JDBC Skill Template

### PR DESCRIPTION
**Pull request by svangapally-cs**
https://cognitivescale.atlassian.net/browse/FAB-2607

### CODE REVIEW

**Comment by mcriscolo-cs** [comment]
Why'd you decide to copy all the plugin code over rather than just give prebuilt artifacts?

**Comment by svangapally-cs** [comment]
> Why'd you decide to copy all the plugin code over rather than just give prebuilt artifacts?
I had the same question Initially and also asked in slack. Anyway, I thought as this is a skill template example, it's better to show code so that users can modify the template as per their needs if required. @lkrishna-cs  Please let me know if we should use a prebuilt image from c12e.

**Review by mcriscolo-cs — APPROVED** [review]
I think this looks fine, I'm still not thrilled about the copying over of the plugin source and having it built by the user.

**Comment by lkrishna-cs** [comment]
Agree with @mcriscolo-cs .  Let us start with this and see if we can simplify it in future.

**Review by lkrishna-cs — APPROVED** [review]

**Pull request merged**
